# Site wide configuration

title: "nmiglio"
description: "This is just a bunch of confusing random notes."
logo: smile120x120.gif # 120x120 px default image used for Twitter summary card
teaser: matrixwall.jpg # 400x250 px default teaser image used in image archive grid
locale: en

url: https://nmiglio.github.io # Used to generate absolute URLs. DO NOT use trailing / ! 
# url: http://localhost:4000 # Use for local development

feed:
  path: atom.xml

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Nicola Migliorini
  email: 
  twitter: NicMigliorini
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
  - _pages
  
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  
 defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
